### ISSUE TITLE
Installation on Ubuntu 18.04 requires undocumented cmake

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/parity-zcash#28]
Installed on a clean Ubuntu 18.04.2 machine. Installed documented dependencies 

```
sudo apt-get install build-essential
```

This failed with:

```
Compiling parking_lot v0.8.0
   Compiling crossbeam-epoch v0.7.0
   Compiling blake2-rfc v0.2.18 (https://github.com/gtank/blake2-rfc.git?rev=7a5b5fc99ae483a0043db7547fb79a6fa44b88a9#7a5b5fc9)
   Compiling blake2b_simd v0.4.1 (https://github.com/oconnor663/blake2b_simd.git#b75a0d10)
   Compiling crossbeam-epoch v0.3.1
error: failed to run custom build command for `parity-snappy-sys v0.1.2`
process didn't exit successfully: `/root/zebra/target/release/build/parity-snappy-sys-c21a77caf3807ec5/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-snappy-sys-0.1.2/snappy" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DCMAKE_INSTALL_PREFIX=/root/zebra/target/release/build/parity-snappy-sys-4f54c8a73765ada8/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=RelWithDebInfo"

--- stderr
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.35/src/lib.rs:778:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Running `sudo apt install cmake` fixed the issue.

**Comment by garethtdavies** [comment]
Are there officially supported distros to test against?

Edit: I see Travis is building on Trusty (Ubuntu 14.04)

**Comment by dconnolly** [comment]
Yeah a few of our dependencies rely on (`cmake, clang, gcc`) being present, we should update the documentation on this point as well as merge in the Dockerfile I've been using on an incoming branch.

**Comment by dconnolly** [comment]
(It's annoying that `build-essential` doesn't include cmake 🙄)

**Comment by dconnolly** [comment]
Travis is currently targeting Trusty, but we're planning to build against Debian Stretch in the future (As well? in addition to? we'll see), and we install `cmake clang gcc` off the bat for that too.

**Comment by dconnolly** [comment]
Yeah it's less obvious because Trusty on Travis includes cmake and clang on top of build-essential by default. https://docs.travis-ci.com/user/reference/trusty/#compilers--build-toolchain

**Comment by dconnolly** [comment]
@garethtdavies I updated the docs as described, but please let me know if you find any other quirks that are not covered.
