### ISSUE TITLE
errors compiling on OSX

### ISSUE THREAD

**Issue by braddmiller** [ZcashFoundation/parity-zcash#4]
Compiling on OSX version 10.14.5 with `rustc` version 1.25.0 fails with multiple instances of two errors:

`error[E0658]: 128-bit type is unstable (see issue #35118)`
`error: unexpected end of macro invocation`

error[E0658] appears to be something fixed in `rustc` version 1.26.0 and later.

Changing default toolchain to `rustc` v1.30.0 and attempting to compile proceeds past these errors but fails with:

`error: Could not compile bitvec`

**Comment by dconnolly** [comment]
We are building against rust stable channel specifically.

**Comment by dconnolly** [comment]
Stable being 1.35.0 currently, does that also error out on your system?

**Comment by braddmiller** [comment]
Compiling now against 1.35.0, almost done. README specifically says rustc min version is 1.23.0 which I'm not sure is accurate.

**Comment by dconnolly** [comment]
Yep that's out of date, will fix. Thanks for catching it!

**Comment by braddmiller** [comment]
1.35.0 compiles fine, so I'm not sure what the actual min version is but it's above 1.30.0 for sure. Ok, closing this issue, thanks!
