### ISSUE TITLE
Checkpoint on Sapling activation

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/parity-zcash#73]
As discussed at Zcon1 with @daira, we should consider removing the Sprout BCTV14 code entirely, and checkpointing on Sapling activation. After Sapling activation, Sprout proofs do Sprout-on-Groth16, so there's no loss of functionality.

This would mean that it's not possible to use Zebra to validate the Zcash chain from genesis, only from Sapling activation, but it's not clear that this is worth the cost and maintainance burden of keeping the Sprout code around forever. The BCTV14 code in Zebra is also uncommented and unreviewed, so we can't use it without putting work into it anyways.

**Comment by dconnolly** [comment]
I wonder if it's good to do this off the bat, or to see if there's a movement of zec out of the Sprout pool into the Sapling pool with updates including banning payments to Sprout addresses, etc.

**Comment by hdevalence** [comment]
Moved this to the `planning` label and milestone.

Note that checkpointing on Sapling activation and removing Sprout proving and verification code doesn't prevent users from spending Sprout pool funds (because after Sapling activation, those proofs do Sprout-on-Groth16).  So there is no issue about people moving ZEC out of the Sprout pool or deciding about whether to ban payments etc.
