### ISSUE TITLE
Rip out bloom filter stuff?

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/parity-zcash#99]
https://github.com/ZcashFoundation/zebra/blob/master/zebra-sync/src/utils/bloom_filter.rs

**Comment by gtank** [comment]
There are related later BIPs that we also don't do, if there's any code for them lying around:

https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0158.mediawiki

**Comment by hdevalence** [comment]
Some version of this is required for BIP37, which is included in Zcash, so we cannot remove it.
